spring:
  application:
    name: constituciones-administracion
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/constituciones
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: ${PORT:8081}
  servlet:
    context-path: /admin

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter: DEBUG
jwt:
  secret: tu_clave_secreta_muy_larga_y_segura_min_32_caracteres
  expiration: 3600
client:
  directorio-activo:
    url: https://4gxis56zai.execute-api.us-east-1.amazonaws.com/prd1/mauc/ldap/oauth/token
    access-key: dGVzdGp3dGNsaWVudGlkOlhZN2ttem9OemwxMDA=
  transversal:
    url: http://localhost:8085/transversal/v1
    access-key: 1HwyCOpBv45tpC5H